import { writable } from 'svelte/store';

export const inventory = writable([
  {
    id: 1,
    name: 'Corgi keyboard',
    description: 'This is a description of the amazing Corgi keyboard',
    category: 'kit',
    price: 1000,
    currency: 'NOK',
    unitsAvailable: 10,
  },
  {
    id: 2,
    name: 'Rhino keyboard',
    description: 'This is a description of the amazing Rhino keyboard',
    category: 'kit',
    price: 1300,
    currency: 'NOK',
    unitsAvailable: 10,
  },
  {
    id: 3,
    name: 'Eagle keyboard',
    description: 'This is a description of the amazing Eagle keyboard',
    category: 'kit',
    price: 1500,
    currency: 'NOK',
    unitsAvailable: 10,
  },
  {
    id: 4,
    name: 'Corgi PCB',
    description: 'This is a description of the Corgi PCB',
    category: 'pcb',
    price: 300,
    currency: 'NOK',
    unitsAvailable: 20,
  },
  {
    id: 5,
    name: 'Rhino PCB',
    description: 'This is a description of the Rhino PCB',
    category: 'pcb',
    price: 400,
    currency: 'NOK',
    unitsAvailable: 20,
  },
  {
    id: 6,
    name: 'Eagle PCB',
    description: 'This is a description of the Eagle PCB',
    category: 'pcb',
    price: 500,
    currency: 'NOK',
    unitsAvailable: 20,
  },
  {
    id: 7,
    name: 'Corgi plate',
    description: 'This is a description of the Corgi plate',
    category: 'plate',
    price: 200,
    currency: 'NOK',
    unitsAvailable: 15,
  },
  {
    id: 8,
    name: 'Rhino plate',
    description: 'This is a description of the Rhino plate',
    category: 'plate',
    price: 300,
    currency: 'NOK',
    unitsAvailable: 15,
  },
  {
    id: 9,
    name: 'Eagle plate',
    description: 'This is a description of the Eagle plate',
    category: 'plate',
    price: 400,
    currency: 'NOK',
    unitsAvailable: 15,
  },
]);
